"""
Basin::Nexus v5.1 - Scoring Gate
The LLM-powered signal classifier that implements the Bifurcated GTM Model.

This module enforces the 0.8 threshold that separates Machine Labor from Human Leverage.
Kills human latency by automating signal routing decisions.
"""

from pydantic import BaseModel, Field
from typing import Literal, Optional
from datetime import datetime
from enum import Enum


class SignalSource(str, Enum):
    """Signal ingestion channels"""
    GITHUB = "GitHub"
    LINKEDIN = "LinkedIn"
    FUNDING = "Funding Alert"
    JOB_POST = "Job Board"
    TECH_STACK = "Tech Stack Change"
    EXEC_MOVE = "Executive Hire"


class SignalTier(str, Enum):
    """Bifurcated routing destinations"""
    HOT = "EXECUTE"          # Score >= 0.8: Push to High-Signal SDR
    WARM = "NURTURE"         # Score 0.5-0.79: Automated sequence
    COLD = "FREEZER"         # Score < 0.5: Archive in Data Jail


class GTMSignal(BaseModel):
    """
    A buyer intent signal captured by the Unified Signal Ledger.
    
    This is the atomic unit that flows through the Bifurcated Engine:
    Ingestion → Scoring → Execution
    """
    source: SignalSource
    company: str = Field(..., description="Target company name")
    intent_type: str = Field(..., description="Specific signal type, e.g., 'GitHub Star', 'Series B Funding'")
    raw_score: float = Field(..., ge=0.0, le=1.0, description="LLM-generated ICP match score (0-1)")
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    metadata: Optional[dict] = Field(default=None, description="Enrichment data: tech stack, team size, etc.")


class ScoringDecision(BaseModel):
    """The routing decision generated by the Nexus Scoring Gate"""
    signal_id: str
    company: str
    tier: SignalTier
    action: str
    reasoning: str
    score: float


def nexus_scoring_gate(signal: GTMSignal) -> ScoringDecision:
    """
    Implements the Basin::Nexus Bifurcated Model.
    
    This is the "Golden Gate" that killed human latency at Fudo Security.
    
    Logic:
    - Score >= 0.8: EXECUTE → High-Signal SDR (Executive Ghostwriting)
    - Score 0.5-0.8: NURTURE → Automated sequence (LLM-driven drip)
    - Score < 0.5: FREEZER → Archive in CRM (Data Jail)
    
    Result: 160% pipeline growth with 50% reduction in manual toil.
    """
    
    # Thresholds that defined the Fudo implementation
    HOT_THRESHOLD = 0.8
    WARM_THRESHOLD = 0.5
    
    if signal.raw_score >= HOT_THRESHOLD:
        tier = SignalTier.HOT
        action = f"EXECUTE: Push {signal.company} to Senior SDR for high-touch outreach"
        reasoning = (
            f"Score {signal.raw_score:.2f} indicates high ICP match. "
            f"Signal from {signal.source.value} ({signal.intent_type}) requires executive ghostwriting. "
            "Human leverage justified."
        )
    
    elif signal.raw_score >= WARM_THRESHOLD:
        tier = SignalTier.WARM
        action = f"NURTURE: Enroll {signal.company} in automated sequence"
        reasoning = (
            f"Score {signal.raw_score:.2f} indicates moderate fit. "
            f"Route to LLM-driven nurture campaign. "
            "Re-score after 30-day engagement window."
        )
    
    else:
        tier = SignalTier.COLD
        action = f"FREEZER: Archive {signal.company} signal in Data Jail (CRM)"
        reasoning = (
            f"Score {signal.raw_score:.2f} is below threshold. "
            f"No immediate action. Store for quarterly review or future re-scoring."
        )
    
    return ScoringDecision(
        signal_id=f"{signal.company}_{signal.timestamp.isoformat()}",
        company=signal.company,
        tier=tier,
        action=action,
        reasoning=reasoning,
        score=signal.raw_score
    )


# Example: Fudo Security Implementation (160% Pipeline Growth Context)
if __name__ == "__main__":
    # Example 1: HOT signal (NVIDIA GitHub activity)
    nvidia_signal = GTMSignal(
        source=SignalSource.GITHUB,
        company="NVIDIA",
        intent_type="New security repo created",
        raw_score=0.92,
        metadata={
            "tech_stack": ["Kubernetes", "Python", "Go"],
            "team_size": 500,
            "funding_stage": "Public"
        }
    )
    
    decision = nexus_scoring_gate(nvidia_signal)
    print(f"\\n🔥 HOT SIGNAL DETECTED")
    print(f"Company: {decision.company}")
    print(f"Tier: {decision.tier.value}")
    print(f"Action: {decision.action}")
    print(f"Reasoning: {decision.reasoning}")
    
    # Example 2: WARM signal (eBay job posting)
    ebay_signal = GTMSignal(
        source=SignalSource.JOB_POST,
        company="eBay",
        intent_type="Hiring Security Engineer",
        raw_score=0.67,
        metadata={
            "tech_stack": ["React", "Node.js"],
            "team_size": 200
        }
    )
    
    decision2 = nexus_scoring_gate(ebay_signal)
    print(f"\\n⚡ WARM SIGNAL DETECTED")
    print(f"Company: {decision2.company}")
    print(f"Tier: {decision2.tier.value}")
    print(f"Action: {decision2.action}")
    
    # Example 3: COLD signal (Low-fit startup)
    cold_signal = GTMSignal(
        source=SignalSource.LINKEDIN,
        company="GenericStartup",
        intent_type="Posted about hiring",
        raw_score=0.28,
        metadata={"team_size": 5}
    )
    
    decision3 = nexus_scoring_gate(cold_signal)
    print(f"\\n❄️  COLD SIGNAL DETECTED")
    print(f"Company: {decision3.company}")
    print(f"Tier: {decision3.tier.value}")
    print(f"Action: {decision3.action}")
